spring:
  cloud:
    azure:
      eventhubs:
        connection-string:
        processor:
          checkpoint-store:
            account-name: messagequeuestorage
            account-key: 
            container-name: topic
    stream:
      bindings:

        consume-in-0:
          destination: messagequeuehub
          group: consumer1
        supply-out-0:
          destination: messagequeuehub

        supplyChange-out-0:
          destination: messagequeuehub

      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      function:
        definition: supply;supplyChange;consume;
      poller:
        initial-delay: 0
        fixed-delay: 1000
